name: GITHUB_OUTPUT
on: push
jobs: 
  share: 
    runs-on: ubuntu-latest
    steps:
        - id: source
          run: echo "result=aおおおお" >> "${GITHUB_OUTPUT}" # github_outputへ書き出し
        - env: 
            RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照
          run: echo "${RESULT}".
